version: "3.9"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: bransgroves_portal
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://user:secretpassword@db:5432/bransgroves_portal
      REDIS_URL: redis://redis:6379/0

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data:
